spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db/changelog/main-changelog.yml
    enabled: true

jwt:
  secret: ${JWT_SECRET}

registration:
  secret-word: ${MY_SECRET_WORD}

user:
  service:
    url: ${REGISTER_USER_URL}
